# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.job_params_jobs import JobParamsJobs  # noqa: F401,E501
from swagger_server import util


class JobParams(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, jobs: List[JobParamsJobs]=None):  # noqa: E501
        """JobParams - a model defined in Swagger

        :param jobs: The jobs of this JobParams.  # noqa: E501
        :type jobs: List[JobParamsJobs]
        """
        self.swagger_types = {
            'jobs': List[JobParamsJobs]
        }

        self.attribute_map = {
            'jobs': 'jobs'
        }

        self._jobs = jobs

    @classmethod
    def from_dict(cls, dikt) -> 'JobParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobParams of this JobParams.  # noqa: E501
        :rtype: JobParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def jobs(self) -> List[JobParamsJobs]:
        """Gets the jobs of this JobParams.


        :return: The jobs of this JobParams.
        :rtype: List[JobParamsJobs]
        """
        return self._jobs

    @jobs.setter
    def jobs(self, jobs: List[JobParamsJobs]):
        """Sets the jobs of this JobParams.


        :param jobs: The jobs of this JobParams.
        :type jobs: List[JobParamsJobs]
        """
        if jobs is None:
            raise ValueError("Invalid value for `jobs`, must not be `None`")  # noqa: E501

        self._jobs = jobs
